### ISSUE TITLE
Java Code Add numpad implementation

### ISSUE THREAD

**Issue by TaylerUva** [FRCTeam3255/Robot2023#185]

**Comment by TaylerUva** [comment]
We need to look into Arduino code

**Comment by ACat701** [comment]
- [ ] Create numpad instance
- [ ] Create logic for wanting a game piece (LEDs, SetLEDs command)
- [ ] Create logic for setting the desired row/column to be used in other methods

**Comment by TaylerUva** [comment]
closed by #192
