### ISSUE TITLE
Pick up tipped cone command

### ISSUE THREAD

**Issue by IanSzalai** [FRCTeam3255/Robot2023#188]
Once bumpers are touching cone base:
- [ ] Lower intake to be hovering past cone base
- [ ] Spin intake (parallel w/ drive)
- [ ] Back up using drivetrain (parallel w/ spin)
- [ ] Stow position

**Comment by TaylerUva** [comment]
Closed as redundant. See details:
https://github.com/FRCTeam3255/Robot2023/pull/196#issuecomment-1442845073
