### ISSUE TITLE
Create dashboard for driver feedback

### ISSUE THREAD

**Issue by TaylerUva** [FRCTeam3255/Robot2023#224]
Should have:
- camera
- isGamePiece collected
- Target Node Column (ideally a true false grid)
- Target Node Height (ideally a true false grid)

(feel free to add more)

**Comment by IanSzalai** [comment]
after phr my thoughts on the dashboard are the following:

* should be extremely simple with the bare minimum information needed
  * if the drivers realize that they are not using information that is being displayed, it should be removed
  * there should not be redundant information between controller rumble, robot LED state, and the dashboard
* we don't need a camera
* the goal node should be a 3x9 grid, NOT a 3x4 or 3x3 grid
