### ISSUE TITLE
Automate pick up tipped cone

### ISSUE THREAD

**Issue by TaylerUva** [FRCTeam3255/Robot2023#263]

**Comment by IanSzalai** [comment]
(in my opinion) we should absolutely not do this without significant modifications. the intake needs to be extremely precisely manipulated to right a tipped cone and without a fast, fully automated sequence (easy part) and very accurate lineup (hard part) this isn't worth it.

there are two things that would make this worth it for me:
1. vision system to recognize orientation of tipped cone, such that an automated sequence wouldn't require a precise lineup on the field.
2. mechanical change to assist in righting cones

one other thing that *might* work: putting the elbow tube at the height of the cone flange and rotating over the cone to push it upright with the elbow tube, but I still don't think this could be made fast enough to actually be worth doing over an lz cycle.

**Comment by IanSzalai** [comment]
https://youtu.be/xnTFqxv5Exw?t=88 this is what I'm thinking we do with our elbow tube. this kinda mechanism could also be integrated with our cube intake
