### ISSUE TITLE
Remove brushless param from Intake motor constructor 

### ISSUE THREAD

**Issue by TaylerUva** [FRCTeam3255/Robot2023#64]
https://github.com/FRCTeam3255/Robot2023/blob/1a170c93f0ec1e016ddeffcaf66550dfbfce24a6/src/main/java/frc/robot/subsystems/Intake.java#L33-L34

The default constructor is already brushless and this makes code changes between SparkMAX and Falcon easier

**Comment by IanSzalai** [comment]
closed by #73
