### ISSUE TITLE
Create Charge Station Climb Command

### ISSUE THREAD

**Issue by Alenguye582** [FRCTeam3255/Robot2023#86]
Uses:
- Drivetrain
- Collector
- Treads

**Comment by ACat701** [comment]
General Climb Process:
- Drive up
- Deploy collector down
- Run all wheels (collector, treads, drivetrain)
- Stop using gyro output
- Enable defense mode (#13)

**Comment by TaylerUva** [comment]
No treads are going on comp bot.
